# Start with the official Selenium Standalone Chrome image
FROM selenium/standalone-chrome:123.0

USER root

# Install Python and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip faketime libfaketime locales locales-all

RUN locale-gen en_US.UTF-8

# Install Selenium for Python
RUN pip3 install selenium

ARG FAKETIME
ENV FAKETIME="${FAKETIME}" LD_PRELOAD="/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1"

USER seluser
ARG FAKETIME
ENV FAKETIME="${FAKETIME}" \
  LD_PRELOAD="/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1" \
  TZ="America/Los_Angeles" \
  LANG=en_US.UTF-8
