services:
  magicmirror:
    container_name: mm-magicmirror
    image: mm-magicmirror
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: 
      - npm
      - run
      - server

  selenium:
    container_name: mm-selenium
    image: mm-selenium
    ports:
      - "4444:4444"
    privileged: true
    shm_size: 2g
