# Start with the official Selenium Standalone Chrome image
FROM selenium/standalone-chrome:117.0-20231004
SHELL ["/bin/bash", "-c"]

USER root

# Update JDK
#RUN apt-get update && \
#    apt-get install -y openjdk-11-jdk && \
#    rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME
#ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64

# Install Python and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-selenium faketime libfaketime locales locales-all lsb-release

# Show the OS version
RUN lsb_release -a

RUN locale-gen en_US.UTF-8

ARG FAKETIME
ENV FAKETIME="${FAKETIME}" LD_PRELOAD="/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1"

USER seluser

# use python virtual environment
RUN python3 -m venv ~/venv --without-pip
RUN source ~/venv/bin/activate

ARG FAKETIME
ENV FAKETIME="${FAKETIME}" \
  LD_PRELOAD="/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1" \
  TZ="America/Los_Angeles" \
  LANG=en_US.UTF-8
