# Start with the official Selenium Standalone Chrome image
FROM selenium/standalone-chrome:latest
SHELL ["/bin/bash", "-c"]

USER root

# Install Python and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip faketime libfaketime locales locales-all pipx

RUN locale-gen en_US.UTF-8

ARG FAKETIME
ENV FAKETIME="${FAKETIME}" LD_PRELOAD="/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1"

USER seluser

# Install Selenium for Python
RUN python3 -m venv ~/venv
RUN source ~/venv/bin/activate
RUN python3 -m pip install selenium

ARG FAKETIME
ENV FAKETIME="${FAKETIME}" \
  LD_PRELOAD="/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1" \
  TZ="America/Los_Angeles" \
  LANG=en_US.UTF-8
